# Generated by Django 5.1.5 on 2025-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
